AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Backend IAM role and policies for CELL-KN tasks template.'
# Stack Name: NLM-SBOX-CELL-KN-ecs-role
# aws cloudformation create-stack \
#   --stack-name NLM-SBOX-CELL-KN-ecs-role \
#   --template-body file://ecs-task-role-and-policy.yaml \
#   --parameters ParameterKey=pAppNameLC,ParameterValue=ecs \
#   --capabilities CAPABILITY_NAMED_IAM

Parameters:
  pAWSAccount:
    Description: Account (NLM-PROD, NLM-QA, NLM-INT, NLM-SEC)
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/pAwsAccount
  pAppNameLC:
    Description: Application Name (lowercase)
    Type: String
    Default: ecs
  pProjectName:
    Type: String
    Default: cell-kn
    Description: Project name for resource naming
  pEnvironment:
    Type: String
    Default: sandbox
    Description: Environment name (dev, sandbox, prod)
    AllowedValues:
      - dev
      - sandbox
      - prod
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project Configuration
        Parameters:
          - pProjectName
          - pEnvironment

Conditions:
  IsDev: !Equals [!Ref pEnvironment, 'sandbox']

Resources:
# ============================================================================
# IAM Roles for backend ECS  Tasks.
# ============================================================================
  BackendSvcRole:
    Type: AWS::IAM::Role
    Condition: IsDev
    Properties:
      RoleName: !Sub "${pAWSAccount}-${pProjectName}-${pAppNameLC}-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
      Policies:
        - PolicyName: !Sub '${pAWSAccount}-${pProjectName}-${pAppNameLC}-SSMAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                Resource: !Sub 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${pProjectName}/${pEnvironment}/*'
        - PolicyName: !Sub '${pAWSAccount}-${pProjectName}-${pAppNameLC}-SecretsManagerAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${pProjectName}/${pEnvironment}/secrets/*'
        - PolicyName: !Sub '${pAWSAccount}-${pProjectName}-${pAppNameLC}-ServiceDiscoveryAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - servicediscovery:RegisterInstance
                  - servicediscovery:DeregisterInstance
                  - servicediscovery:GetOperation
                Resource: '*'
        - PolicyName: !Sub '${pAWSAccount}-${pProjectName}-${pAppNameLC}-CloudWatchLogsAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/${pProjectName}-${pEnvironment}-backend:*'
      Tags:
        - Key: Project
          Value: !Ref pProjectName
        - Key: pEnvironment
          Value: !Ref pEnvironment
        - Key: Name
          Value: !Sub '${pProjectName}-${pEnvironment}-backend-svc-role'
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  BackendSvcRoleArn:
    Condition: IsDev
    Description: ARN of the IAM role for backend ECS tasks
    Value: !GetAtt BackendSvcRole.Arn
    Export:
      Name: !Sub '${pProjectName}-${pEnvironment}-backend-instance-role-arn'
